EfCoreSqlAndCosmos/Controllers/AdminController.cs
// Copyright (c) 2019 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using DataLayer.EfCode;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.BooksSqlWithEvents;
using ServiceLayer.DatabaseServices.Concrete;

namespace EfCoreSqlAndCosmos.Controllers
{
    public class AdminController : BaseTraceController
    {
        //------------------------------------------------
        //Admin commands that are called from the top menu

        public IActionResult ResetCacheValues([FromServices]IHardResetCacheService service)
        {
            var status = service.CheckUpdateBookCacheProperties();
            return View("Message", status.Message);
        }

        public IActionResult ResetDatabase(
            [FromServices]SqlDbContext context,
            [FromServices]NoSqlDbContext noSqlDbContext,
            [FromServices]IWebHostEnvironment env)
        {
            context.DevelopmentWipeCreated(noSqlDbContext);
            var numBooks = context.SeedDatabase(env.WebRootPath);
            SetupTraceInfo();
            return View("Message", $"Successfully reset the database and added {numBooks} books.");
        }
    }
}

EfCoreSqlAndCosmos/Controllers/SqlEventsController.cs
// Copyright (c) 2019 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.EfClassesSql;
using DataLayerEvents.EfCode;
using EfCoreSqlAndCosmos.HelperCode;
using GenericServices;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.BooksCommon;
using ServiceLayer.BooksSql;
using ServiceLayer.BooksSql.Dtos;
using ServiceLayer.BooksSqlWithEvents;
using ServiceLayer.BooksSqlWithEvents.Dtos;
using ServiceLayer.Logger;

namespace EfCoreSqlAndCosmos.Controllers
{
    public class SqlEventsController : BaseTraceController
    {
        public IActionResult Index (SqlSortFilterPageOptions options, [FromServices]ISqlEventsListBooksService service)
        {
            var output = service.SortFilterPage(options).ToList();
            SetupTraceInfo();
            return View(new SqlBookListCombinedDto(options, output));              
        }

        /// <summary>
        /// This provides the filter search dropdown content
        /// </summary>
        /// <param name="options"></param>
        /// <param name="service"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetFilterSearchContent    
            (SqlSortFilterPageOptions options, [FromServices]IBookEventsFilterDropdownService service)         
        {

            var traceIdent = HttpContext.TraceIdentifier; 
            return Json(                            
                new TraceIndentGeneric<IEnumerable<DropdownTuple>>(
                traceIdent,
                service.GetFilterDropDownValues(  options.FilterBy)));            
        }

        //-------------------------------------------------------

        public IActionResult ChangePubDate(Guid id, [FromServices]ICrudServices<SqlEventsDbContext> service)
        {
            var dto = service.ReadSingle<ChangePubDateEventsDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePubDate(ChangePubDateEventsDto dto, [FromServices]ICrudServicesAsync<SqlEventsDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            await service.UpdateAndSaveAsync(dto);
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }

        public IActionResult AddPromotion(Guid id, [FromServices]ICrudServices<SqlEventsDbContext> service)
        {
            var dto = service.ReadSingle<AddRemovePromotionEventsDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPromotion(AddRemovePromotionEventsDto dto, [FromServices]ICrudServices<SqlEventsDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            service.UpdateAndSave(dto, nameof(Book.AddPromotion));
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }

        public IActionResult RemovePromotion(Guid id, [FromServices]ICrudServices<SqlEventsDbContext> service)
        {
            var dto = service.ReadSingle<AddRemovePromotionEventsDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemovePromotion(AddRemovePromotionEventsDto dto, [FromServices]ICrudServices<SqlEventsDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            service.UpdateAndSave(dto, nameof(Book.RemovePromotion));
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }


        public IActionResult AddBookReview(Guid id, [FromServices]ICrudServices<SqlEventsDbContext> service)
        {
            var dto = service.ReadSingle<AddReviewEventsDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddBookReview(AddReviewEventsDto dto, [FromServices]ICrudServices<SqlEventsDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            service.UpdateAndSave(dto);
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }

    }
}

EfCoreSqlAndCosmos/Views/Admin/AddBookReview.cshtml
@model ServiceLayer.BooksSql.Dtos.AddReviewDto



<h2>Add a book review</h2>

<div class="form-horizontal">
    <form asp-controller="Admin" asp-action="AddBookReview" method="post">
        <!-- Input and Submit elements -->
        <input name="BookId" type="hidden" value="@Model.BookId" />
        
        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Book Title</label>
            </div>
            <div class="col-sm-10">
                @ViewData["BookTitle"]
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">YourName</label>
            </div>
            <input asp-for="VoterName" class="form-control col-sm-10" />
        </div>
        
        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Grade (0 to 5)</label>
            </div>
            <input asp-for="NumStars" min="0" max="5" class="form-control col-sm-10" />
        </div>
        
        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Your comment</label>
            </div>
            <textarea  asp-for="Comment" class="form-control col-sm-10"></textarea>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit">Update</button>
            </div>
        </div>

    </form>
</div>

EfCoreSqlAndCosmos/Views/Admin/ChangePromotion.cshtml
@model DataLayer.EfClasses.PriceOffer



<h2>Add/change Book Promotion</h2>

<div class="form-horizontal">
    <form asp-controller="Admin" asp-action="ChangePromotion" method="post">
        <!-- Input and Submit elements -->
        <input name="BookId" type="hidden" value="@Model.BookId" />
        
        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Book Title</label>
            </div>
            <div class="col-sm-10">
                @ViewData["BookTitle"]
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Org Price</label>
            </div>
            <div class="col-sm-10">
                @ViewData["OrgPrice"]
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">New Price</label>
            </div>
            <input asp-for="NewPrice" class="form-control col-sm-10" />
        </div>
        
        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Promotional Text</label>
            </div>
            <input asp-for="PromotionalText" class="form-control col-sm-10" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit">Update</button>
            </div>
        </div>

    </form>
</div>

EfCoreSqlAndCosmos/Views/Admin/ChangePubDate.cshtml
@model ServiceLayer.BooksSql.Dtos.ChangePubDateDto
@{
    ViewBag.Title = "title";
}

<h2>Change Publication Date</h2>
<div class="form-horizontal">
    <form asp-controller="Admin" asp-action="ChangePubDate" method="post">
        <!-- Input and Submit elements -->
        <input name="BookId" type="hidden" value="@Model.BookId" />

        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Book Title</label>
            </div>
                <div class="col-sm-10">
                    @Model.Title
                </div>
        </div>

        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Publication Date</label>
            </div>
            <input asp-for="PublishedOn" class="form-control col-sm-10" />
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit">Update</button>
            </div>
        </div>

    </form>
</div>

EfCoreSqlAndCosmos/Views/Admin/Message.cshtml
@model string

<h2>@Model</h2>

<p>You can see the change by going to.</p>
<ul>
    <li>@Html.ActionLink("Sql Books", "Index", "Home")</li>
    <li>@Html.ActionLink("Sql Events Books", "Index", "SqlEvents")</li>
</ul>