EfCoreSqlAndCosmos/Controllers/GenerateController.cs
// Copyright (c) 2019 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using DataLayer.EfCode;
using DataLayer.NoSqlCode;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage;
using ServiceLayer.DatabaseServices.Concrete;

namespace EfCoreSqlAndCosmos.Controllers
{
    public class GenerateController : BaseTraceController
    {

        // GET
        public IActionResult Index([FromServices]SqlDbContext context)
        {
            return View(context.Books.Count());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Books(int totalBooksNeeded, bool wipeDatabase, CancellationToken cancellationToken,
            [FromServices]SqlDbContext sqlContext,
            [FromServices]BookGenerator generator,
            [FromServices]IWebHostEnvironment env)
        {
            if (totalBooksNeeded == 0)
                return View((object) "Error: should contain the number of books to generate.");

            NoSqlDbContext noSqlContext = (NoSqlDbContext) HttpContext.RequestServices.GetService(typeof(NoSqlDbContext));

            if (wipeDatabase)
                sqlContext.DevelopmentWipeCreated(noSqlContext);

            var filepath = Path.Combine(env.WebRootPath, SetupHelpers.SeedFileSubDirectory,
                SetupHelpers.TemplateFileName);
            await generator.WriteBooksAsync(filepath, totalBooksNeeded, true, cancellationToken);

            SetupTraceInfo();

            return
                View((object) ((cancellationToken.IsCancellationRequested ? "Cancelled" : "Successful") +
                     $" generate. Num books in database = {sqlContext.Books.Count()}."));
        }

        [HttpPost]
        public ActionResult NumBooks([FromServices]SqlDbContext context)
        {
            var dbExists = (context.Database.GetService<IDatabaseCreator>() as RelationalDatabaseCreator).Exists();
            var message = dbExists ? $"Num books = {context.Books.Count()}" : "database being wiped.";
            return Content(message);
        }
    }
}

EfCoreSqlAndCosmos/Views/Generate/Books.cshtml
@model string

@{
    ViewBag.Title = "title";
}

<h2>Generate finished</h2>

<h4>@Model</h4>

EfCoreSqlAndCosmos/Views/Generate/Index.cshtml
@model int


<h2>How many books do you want to have?</h2>
<h4>There are currenty <strong>@Model.ToString("##,###") books</strong> in the SQL database.</h4>

<h3 class="text-danger">WARNING!</h3>
<p class="text-danger">
    This can take a LONG time! On my (fast) PC it takes 2 minutes to generate 10,000 books with associated NoSQL entries.
    I have added a web.config file with a requestTimeout of 20 minutes, so that it doesn't time out the action
</p>

<div class="form-horizontal">
    <form asp-controller="Generate" asp-action="Books" method="post" id="input-form">
        <!-- Input and Submit elements -->

        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Total books you want</label>
            </div>
            <div class="col-sm-10">
                 <input name="totalBooksNeeded" id="totalBooksNeeded" value="10000" class="form-control col-sm-10" />
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-sm-2">
                <label class="control-label">Wipe database?</label>
            </div>
            <div class="col-sm-1">
                <input type="checkbox" name="wipeDatabase" value="true" class="form-control" />
                <input type="hidden" name="wipeDatabase" value="false" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" onclick="startGenerate()">Generate</button>
            </div>
        </div>

    </form>

</div>

<p>
    <strong>NOTE:</strong> to stop the generator refresh this page, or go to a different page. It stops at the next batch update.
    <br/>
    <i>Thanks to Andrew Lock's <a href="https://andrewlock.net/using-cancellationtokens-in-asp-net-core-mvc-controllers/">Using CancellationTokens in ASP.NET Core MVC controllers</a> article for how to do that.</i>
</p>
<hr/>
<H4 id="show-num-books" class="hidden">

</H4> 

<script>
    function startGenerate() {
        var form = $('#input-form');
        startUpdatingProgressIndicator();
        $.post(
            form.attr('action'),
            form.serialize
        );
    }

    var intervalId;

    function startUpdatingProgressIndicator() {
        var $progress = $("#show-num-books");
        $progress.removeClass('hidden');

        var skipFirst = true;
        intervalId = setInterval(
            function () {
                // We use the POST requests here to avoid caching problems (we could use the GET requests and disable the cache instead)
                $.post(
                    '@Url.Action("NumBooks")',
                    {},
                    function (data, status) {
                        if (skipFirst) {
                            skipFirst = false;
                            return;
                        }
                        $progress.html(data);
                    }
                );
            },
            1000
        );
    }

    function stopUpdatingProgressIndicator() {
        clearInterval(intervalId);
    }
</script>