EfCoreSqlAndCosmos/Controllers/AdminController.cs
// Copyright (c) 2019 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using DataLayer.EfCode;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.BooksSqlWithEvents;
using ServiceLayer.DatabaseServices.Concrete;

namespace EfCoreSqlAndCosmos.Controllers
{
    public class AdminController : BaseTraceController
    {
        //------------------------------------------------
        //Admin commands that are called from the top menu

        public IActionResult ResetCacheValues([FromServices]IHardResetCacheService service)
        {
            var status = service.CheckUpdateBookCacheProperties();
            return View("Message", status.Message);
        }

        public IActionResult ResetDatabase(
            [FromServices]SqlDbContext context,
            [FromServices]NoSqlDbContext noSqlDbContext,
            [FromServices]IWebHostEnvironment env)
        {
            context.DevelopmentWipeCreated(noSqlDbContext);
            var numBooks = context.SeedDatabase(env.WebRootPath);
            SetupTraceInfo();
            return View("Message", $"Successfully reset the database and added {numBooks} books.");
        }
    }
}

EfCoreSqlAndCosmos/Controllers/LoggerController.cs
// Copyright (c) 2019 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using Microsoft.AspNetCore.Mvc;
using ServiceLayer.Logger;

namespace EfCoreSqlAndCosmos.Controllers
{
    public class LoggerController : Controller
    {
        [HttpGet]
        public JsonResult GetLog(string traceIdentifier)
        {
            return Json(HttpRequestLog.GetHttpRequestLog(traceIdentifier));
        }
    }
}

EfCoreSqlAndCosmos/Controllers/NoSqlController.cs
// Copyright (c) 2019 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ServiceLayer.BooksCommon;
using ServiceLayer.BooksNoSql;
using ServiceLayer.Logger;

namespace EfCoreSqlAndCosmos.Controllers
{
    public class NoSqlController : BaseTraceController
    {
        public async Task<IActionResult> Index (NoSqlSortFilterPageOptions options, [FromServices] IListNoSqlBooksService service)
        {
            var output = await service.SortFilterPageAsync(options);
            SetupTraceInfo();
            return View(new NoSqlBookListCombinedDto(options, output));              
        }


        /// <summary>
        /// This provides the filter search dropdown content
        /// </summary>
        /// <param name="options"></param>
        /// <param name="service"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<JsonResult> GetFilterSearchContent    
            (NoSqlSortFilterPageOptions options, [FromServices]IBookNoSqlFilterDropdownService service)         
        {

            var traceIdent = HttpContext.TraceIdentifier; 
            return Json(                            
                new TraceIndentGeneric<IEnumerable<DropdownTuple>>(
                traceIdent,
                await service.GetFilterDropDownValuesAsync(options.FilterBy)));            
        }

    }
}

EfCoreSqlAndCosmos/Controllers/SqlController.cs
// Copyright (c) 2019 Jon P Smith, GitHub: JonPSmith, web: http://www.thereformedprogrammer.net/
// Licensed under MIT license. See License.txt in the project root for license information.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataLayer.EfClassesSql;
using DataLayer.EfCode;
using EfCoreSqlAndCosmos.HelperCode;
using GenericServices;
using Microsoft.AspNetCore.Mvc;
using ServiceLayer.BooksCommon;
using ServiceLayer.BooksSql;
using ServiceLayer.BooksSql.Dtos;
using ServiceLayer.Logger;

namespace EfCoreSqlAndCosmos.Controllers
{
    public class SqlController : BaseTraceController
    {
        public IActionResult Index (SqlSortFilterPageOptions options, [FromServices] ISqlListBooksService service)
        {
            var output = service.SortFilterPage(options).ToList();
            SetupTraceInfo();
            return View(new SqlBookListCombinedDto(options, output));              
        }

        /// <summary>
        /// This provides the filter search dropdown content
        /// </summary>
        /// <param name="options"></param>
        /// <param name="service"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult GetFilterSearchContent    
            (SqlSortFilterPageOptions options, [FromServices]IBookFilterDropdownService service)         
        {

            var traceIdent = HttpContext.TraceIdentifier; 
            return Json(                            
                new TraceIndentGeneric<IEnumerable<DropdownTuple>>(
                traceIdent,
                service.GetFilterDropDownValues(  options.FilterBy)));            
        }


        //-------------------------------------------------------

        public IActionResult ChangePubDate(Guid id, [FromServices]ICrudServices<SqlDbContext> service)
        {
            var dto = service.ReadSingle<ChangePubDateDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ChangePubDate(ChangePubDateDto dto, [FromServices]ICrudServicesAsync<SqlDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            await service.UpdateAndSaveAsync(dto);
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }

        public IActionResult AddPromotion(Guid id, [FromServices]ICrudServices<SqlDbContext> service)
        {
            var dto = service.ReadSingle<AddRemovePromotionDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPromotion(AddRemovePromotionDto dto, [FromServices]ICrudServices<SqlDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            service.UpdateAndSave(dto, nameof(Book.AddPromotion));
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }

        public IActionResult RemovePromotion(Guid id, [FromServices]ICrudServices<SqlDbContext> service)
        {
            var dto = service.ReadSingle<AddRemovePromotionDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RemovePromotion(AddRemovePromotionDto dto, [FromServices]ICrudServices<SqlDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            service.UpdateAndSave(dto, nameof(Book.RemovePromotion));
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }


        public IActionResult AddBookReview(Guid id, [FromServices]ICrudServices<SqlDbContext> service)
        {
            var dto = service.ReadSingle<AddReviewDto>(id);
            if (!service.IsValid)
            {
                service.CopyErrorsToModelState(ModelState, dto);
            }
            SetupTraceInfo();
            return View(dto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddBookReview(AddReviewDto dto, [FromServices]ICrudServices<SqlDbContext> service)
        {
            if (!ModelState.IsValid)
            {
                return View(dto);
            }
            service.UpdateAndSave(dto);
            SetupTraceInfo();
            if (service.IsValid)
                return View("BookUpdated", service.Message);

            //Error state
            service.CopyErrorsToModelState(ModelState, dto);
            return View(dto);
        }
    }
}

EfCoreSqlAndCosmos/Views/Shared/LogModal.cshtml
@* // sends in the number of logs *@

<!-- Logs Modal -->
<div class="modal fade" id="log-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Logs (<span></span>)</h4>
            </div>
            <div class="modal-body">
                <p>One fine body&hellip;</p>
            </div>
            <div class="modal-footer">
                <div class="pull-left">
                    <span class="label label-default">Show</span>
                    <div id="displaySelect" class="btn-group" data-toggle="buttons" aria-label="select log types">
                        <label id="all-select" class="btn btn-default">
                            <input type="radio" value="all" name="displaySelect">All&nbsp;(<span></span>)
                        </label>
                        <label id="sql-select" class="btn btn-default active">
                            <input type="radio" value="sql" name="displaySelect" checked>SQL&nbsp;(<span></span>)
                        </label>
                    </div>
                </div>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

EfCoreSqlAndCosmos/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EfCoreSqlAndCosmos</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EfCoreSqlAndCosmos</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Sql" asp-action="Index">Books (SQL)</a></li>
                    <li><a asp-area="" asp-controller="SqlEvents" asp-action="Index">Books, event updates</a></li>
                    @if (Configuration["StartupMode"] == StartupModes.SqlAndCosmosDb.ToString())
                    {
                        <li><a asp-area="" asp-controller="NoSql" asp-action="Index">Books (NoSQL)</a></li>
                    }
                    <li><a href="#" id="show-logs" class="hidden">Logs&nbsp;<span class="badge"></span></a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Admin
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="dropdownAdminItems">
                            <li><a asp-area="" asp-controller="Admin" asp-action="ResetCacheValues">Reset Cache Values</a></li>
                            <li><a asp-area="" asp-controller="Admin" asp-action="ResetDatabase">Reset Database</a></li>
                            <li><a asp-area="" asp-controller="Generate" asp-action="Index">Generate Books</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
        @Html.Partial("LogModal")
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - EfCoreSqlAndCosmos
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/loggingDisplay.js" asp-append-version="true"></script>
        <script src="~/js/bookList.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/bundle.min.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)

    <script type='text/javascript'>
    document.addEventListener("DOMContentLoaded",
        function(event) {
            var numLogs = @(ViewData["NumLogs"] ?? 0);
            if (numLogs > 0) {
                LoggingDisplay.initialise('@Url.Action("GetLog", "Logger")', '@ViewData["TraceIdent"]', numLogs);
            }
        });
    </script>
</body>
</html>